[package]
name = "hangman"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colorful = "0.2.1"
owo-colors = "2.0.0"
rand = "0.8.4"
text_io = "0.1.8"
